/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package revisioncrudswing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyril
 */
public class CrudSurUneTable extends javax.swing.JFrame {

    /**
     * Creates new form CrudSurUneTable
     */
    public CrudSurUneTable() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("Avenants pays");

        /*
        Remplissage de la jtable
         */
        //Declaration de variables
        Object[] tEntete;
        Object[] tDataLigne;
        Object[][] tTable;
        ResultSetMetaData mtd;

        //Connexion
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/cours", "root", "");
            String lSql = "SELECT * FROM pays ";
            Statement pst = cn.createStatement();
            ResultSet rsl = pst.executeQuery(lSql);

            //Recupération de la structure de la table
            mtd = rsl.getMetaData();

            //Recupération du nombre de colonne
            int liColonne = mtd.getColumnCount();

            //Remplissage de l en tete
            tEntete = new Object[liColonne];
            for (int i = 0; i < liColonne; i++) {

                tEntete[i] = mtd.getColumnName(i + 1);

            }

            //Remplissage des données
            //recuperation du nombre de ligne
            // rsl.last();
            rsl.last();
            int nbLigne = rsl.getRow();

            //le tableau des données
            tTable = new Object[nbLigne][liColonne];
            rsl.beforeFirst();

            //rsl.beforeFirst();
            //int i = 0;
            int t = 0;
            while (rsl.next()) {

                //on remplit ligne par ligne
                tDataLigne = new Object[liColonne];
                for (int j = 0; j < liColonne; j++) {

                    tDataLigne[j] = rsl.getObject(j + 1).toString();

                }
                tTable[t] = tDataLigne;
                t++;

            }//while

            //affectation des tableaux à la jTable
            jTablePays.setModel(new DefaultTableModel(tTable, tEntete));

            rsl.close();
            pst.close();
            cn.close();

        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }//try catch
        jTablePays.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        /*
       Recuperer la valeur de la ligne selectionnée
         */

    }//CrudSurUneTable

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePays = new javax.swing.JTable();
        jLabelIdPays = new javax.swing.JLabel();
        jTextFieldIdPays = new javax.swing.JTextField();
        jLabelNomPays = new javax.swing.JLabel();
        jTextFieldPays = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jButtonEffacer = new javax.swing.JButton();
        jLabelNouvelId = new javax.swing.JLabel();
        jTextFieldNouvelId = new javax.swing.JTextField();
        jLabelNouveauNom = new javax.swing.JLabel();
        jTextFieldNouveauNom = new javax.swing.JTextField();
        jButtonNouvelId = new javax.swing.JButton();
        jButtonNouveauNom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePaysMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePays);

        jLabelIdPays.setText("ID Pays");

        jTextFieldIdPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdPaysActionPerformed(evt);
            }
        });

        jLabelNomPays.setText("Nom du pays");

        jTextFieldPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaysActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonEffacer.setText("Effacer");
        jButtonEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEffacerActionPerformed(evt);
            }
        });

        jLabelNouvelId.setText("Nouvel id");

        jLabelNouveauNom.setText("Nouveau nom");

        jButtonNouvelId.setText("Valider le nouvel Id");
        jButtonNouvelId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNouvelIdActionPerformed(evt);
            }
        });

        jButtonNouveauNom.setText("Valider nouveau nom");
        jButtonNouveauNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNouveauNomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelNouvelId, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNouvelId, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelNouveauNom)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNouveauNom, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelIdPays, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldIdPays, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelNomPays)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldPays, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButtonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(148, 148, 148)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonNouvelId, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                            .addComponent(jButtonNouveauNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdPays, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomPays)
                    .addComponent(jTextFieldPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEffacer))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonSupprimer)
                    .addComponent(jButtonModifier))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNouvelId)
                            .addComponent(jTextFieldNouvelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jButtonNouvelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNouveauNom)
                            .addComponent(jTextFieldNouveauNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNouveauNom)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/cours", "root", "");
            String lSql = "DELETE FROM pays WHERE nom_pays =?";
            //Statement pst = cn.createStatement();
            PreparedStatement lpst = cn.prepareStatement(lSql);
            //lpst.setString(1, jTextFieldIdPays.getText());
            lpst.setString(1, jTextFieldPays.getText());
            int nbInsert = lpst.executeUpdate();
            jLabelMessage.setText(jTextFieldPays.getText() + " a bien été suprimé.");

        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jTextFieldPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaysActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/cours", "root", "");
            String lSql = "INSERT INTO pays (id_pays,nom_pays)VALUES(?,?)";
            //Statement pst = cn.createStatement();
            PreparedStatement lpst = cn.prepareStatement(lSql);
            lpst.setString(1, jTextFieldIdPays.getText());
            lpst.setString(2, jTextFieldPays.getText());
            int nbInsert = lpst.executeUpdate();
            jLabelMessage.setText(jTextFieldPays.getText() + " a bien été ajouté.");

        } catch (SQLException e) {
            e.getMessage();
        }


    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jTextFieldIdPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdPaysActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldIdPaysActionPerformed

    private void jTablePaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePaysMouseClicked
        // TODO add your handling code here:
        int ligneSelect = jTablePays.getSelectedRow();
        String idSelect = jTablePays.getValueAt(ligneSelect, 0).toString();
        String paysSelect = jTablePays.getValueAt(ligneSelect, 1).toString();
        jTextFieldPays.setText(paysSelect);
        jTextFieldIdPays.setText(idSelect);
    }//GEN-LAST:event_jTablePaysMouseClicked

    private void jButtonEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEffacerActionPerformed
        jTextFieldIdPays.setText("");
        jTextFieldPays.setText("");
         jTextFieldNouvelId.setText("");
          jTextFieldNouveauNom.setText("");
    }//GEN-LAST:event_jButtonEffacerActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed

        jTextFieldNouvelId.setText(jTextFieldIdPays.getText());
        jTextFieldNouveauNom.setText(jTextFieldPays.getText());
        

    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonNouvelIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNouvelIdActionPerformed
       try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/cours", "root", "");

            String lSql = "UPDATE pays SET id_pays =? WHERE nom_pays =?";

            //Statement pst = cn.createStatement();
            PreparedStatement lpst = cn.prepareStatement(lSql);
            lpst.setString(1, jTextFieldNouvelId.getText());
            lpst.setString(2, jTextFieldPays.getText());
            
            int nbInsert = lpst.executeUpdate();
            jLabelMessage.setText("Le nouvel Id "+ jTextFieldNouvelId.getText() + " a bien été modifié.");

        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jButtonNouvelIdActionPerformed

    private void jButtonNouveauNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNouveauNomActionPerformed
       
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/cours", "root", "");

            String lSql = "UPDATE pays SET nom_pays =?  WHERE id_pays = ?";

            //Statement pst = cn.createStatement();
            PreparedStatement lpst = cn.prepareStatement(lSql);
            lpst.setString(1, jTextFieldNouveauNom.getText());
            lpst.setString(2, jTextFieldIdPays.getText());
            
            int nbInsert = lpst.executeUpdate();
            jLabelMessage.setText("Le nouveau nom "+ jTextFieldNouveauNom.getText() + " a bien été modifié.");

            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButtonNouveauNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudSurUneTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudSurUneTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudSurUneTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudSurUneTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudSurUneTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonEffacer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonNouveauNom;
    private javax.swing.JButton jButtonNouvelId;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabelIdPays;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelNomPays;
    private javax.swing.JLabel jLabelNouveauNom;
    private javax.swing.JLabel jLabelNouvelId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePays;
    private javax.swing.JTextField jTextFieldIdPays;
    private javax.swing.JTextField jTextFieldNouveauNom;
    private javax.swing.JTextField jTextFieldNouvelId;
    private javax.swing.JTextField jTextFieldPays;
    // End of variables declaration//GEN-END:variables
}//main
